export type Severity = 'Critical' | 'Important' | 'Moderate' | 'Minor';
export type Complexity =
  'Standard' | 'Complex' | 'Extensive' | 'Ecosystem Unavailable' | "Won't Fix";
export type Stage =
  | 'Submitted'
  | 'Classified'
  | 'Fix in Progress'
  | 'Validation'
  | 'Lightwell Network'
  | 'Upstreaming'
  | 'Published';

export const STAGES: Stage[] = [
  'Submitted',
  'Classified',
  'Fix in Progress',
  'Validation',
  'Lightwell Network',
];

export const STAGE_DESCRIPTIONS: Record<Stage, string> = {
  Submitted:
    'Vulnerability submitted, undergoing initial review to determine complexity and identify fixed target.',
  Classified: 'Assessed for complexity; fixed target identified.',
  'Fix in Progress': 'A fix is currently under development.',
  Validation: 'The fix is being validated within the Red Hat pipeline.',
  'Lightwell Network': 'The fix is available in the Lightwell Repository.',
  Upstreaming: 'The fix is being shared with the upstream community following embargo guidelines.',
  Published: 'No longer embargoed; available in upstream repos.',
};

export const COMPLEXITY_SLA: Record<Complexity, number | null> = {
  Standard: 3,
  Complex: 8,
  Extensive: 16,
  'Ecosystem Unavailable': null,
  "Won't Fix": null,
};

export type CustomerPriority = 'Priority 1' | 'Priority 2' | 'Priority 3' | 'Priority 4';

export interface Vulnerability {
  uuid: string;
  vulnerabilityId: string;
  purl: string;
  componentName: string;
  componentVersion: string;
  title: string;
  cwe: string;
  description: string;
  severity: Severity;
  cvss: number;
  cvssVector?: string;
  exploitTested: boolean;
  reproducerIncluded: boolean;
  customerPriority?: CustomerPriority;
  stage: Stage;
  complexity: Complexity;
  submittedDate: string;
  lastUpdated: string;
  ageDays: number;
  embargo: boolean;
  duplicate: boolean;
  duplicateOf?: string;
  ltwlsupt_ticket_id?: string;
  ltwlsupt_ticket_ids?: string[];
}

function daysAgo(days: number): string {
  const d = new Date();
  d.setDate(d.getDate() - days);
  return d.toISOString().split('T')[0];
}

function daysAgoTimestamp(days: number): string {
  const d = new Date();
  d.setDate(d.getDate() - days);
  d.setHours(9 + (days % 8), (days * 17) % 60, (days * 7) % 60);
  return d.toISOString().replace('T', ' ').substring(0, 16);
}

export const mockVulnerabilities: Vulnerability[] = [
  // Submitted (8) - batch-2 (5), batch-3 (3)
  {
    uuid: 'v1',
    vulnerabilityId: 'LWL-2026-4401',
    purl: 'pkg:maven/org.apache.logging.log4j/log4j-core@2.17.1',
    componentName: 'log4j-core',
    componentVersion: '2.17.1',
    title: 'JNDI injection via crafted log message',
    cwe: 'CWE-917',
    description: 'Remote code execution through JNDI lookup in log messages',
    severity: 'Critical',
    cvss: 9.8,
    cvssVector: 'CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H',
    exploitTested: true,
    reproducerIncluded: true,
    customerPriority: 'Priority 1',
    stage: 'Submitted',
    complexity: 'Extensive',
    submittedDate: daysAgo(2),
    lastUpdated: daysAgoTimestamp(1),
    ageDays: 2,
    embargo: true,
    duplicate: false,
    ltwlsupt_ticket_id: 'batch-2',
  },
  {
    uuid: 'v2',
    vulnerabilityId: 'LWL-2026-4402',
    purl: 'pkg:maven/com.fasterxml.jackson.core/jackson-databind@2.14.0',
    componentName: 'jackson-databind',
    componentVersion: '2.14.0',
    title: 'Deserialization gadget chain in TemplatesImpl',
    cwe: 'CWE-502',
    description: 'Unsafe deserialization allows arbitrary code execution',
    severity: 'Important',
    cvss: 8.1,
    cvssVector: 'CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:H/I:H/A:H',
    exploitTested: true,
    reproducerIncluded: true,
    customerPriority: 'Priority 1',
    stage: 'Submitted',
    complexity: 'Complex',
    submittedDate: daysAgo(1),
    lastUpdated: daysAgoTimestamp(0),
    ageDays: 1,
    embargo: false,
    duplicate: false,
    ltwlsupt_ticket_id: 'batch-2',
  },
  {
    uuid: 'v3',
    vulnerabilityId: 'LWL-2026-4403',
    purl: 'pkg:maven/org.springframework/spring-web@5.3.20',
    componentName: 'spring-web',
    componentVersion: '5.3.20',
    title: 'HTTP request smuggling via malformed headers',
    cwe: 'CWE-444',
    description: 'Request smuggling through inconsistent header parsing',
    severity: 'Important',
    cvss: 7.5,
    cvssVector: 'CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:H/A:N',
    exploitTested: true,
    reproducerIncluded: false,
    customerPriority: 'Priority 2',
    stage: 'Submitted',
    complexity: 'Complex',
    submittedDate: daysAgo(3),
    lastUpdated: daysAgoTimestamp(2),
    ageDays: 3,
    embargo: false,
    duplicate: false,
    ltwlsupt_ticket_id: 'batch-2',
  },
  {
    uuid: 'v4',
    vulnerabilityId: 'LWL-2026-4404',
    purl: 'pkg:pypi/requests@2.28.0',
    componentName: 'requests',
    componentVersion: '2.28.0',
    title: 'SSRF via redirect handling',
    cwe: 'CWE-918',
    description: 'Server-side request forgery through unvalidated redirects',
    severity: 'Moderate',
    cvss: 5.3,
    cvssVector: 'CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:N/A:N',
    exploitTested: false,
    reproducerIncluded: false,
    customerPriority: 'Priority 3',
    stage: 'Submitted',
    complexity: 'Standard',
    submittedDate: daysAgo(1),
    lastUpdated: daysAgoTimestamp(0),
    ageDays: 1,
    embargo: false,
    duplicate: false,
    ltwlsupt_ticket_id: 'batch-3',
  },
  {
    uuid: 'v5',
    vulnerabilityId: 'LWL-2026-4405',
    purl: 'pkg:npm/express@4.18.2',
    componentName: 'express',
    componentVersion: '4.18.2',
    title: 'Path traversal in static file serving',
    cwe: 'CWE-22',
    description: 'Directory traversal allows reading arbitrary files',
    severity: 'Important',
    cvss: 7.5,
    cvssVector: 'CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:N',
    exploitTested: true,
    reproducerIncluded: true,
    customerPriority: 'Priority 1',
    stage: 'Submitted',
    complexity: 'Complex',
    submittedDate: daysAgo(4),
    lastUpdated: daysAgoTimestamp(3),
    ageDays: 4,
    embargo: true,
    duplicate: false,
    ltwlsupt_ticket_id: 'batch-2',
  },
  {
    uuid: 'v6',
    vulnerabilityId: 'LWL-2026-4406',
    purl: 'pkg:maven/commons-io/commons-io@2.11.0',
    componentName: 'Apache Commons IO',
    componentVersion: '2.11.0',
    title: 'Infinite loop via crafted ZIP entry',
    cwe: 'CWE-835',
    description: 'Denial of service through malicious archive processing',
    severity: 'Moderate',
    cvss: 5.5,
    cvssVector: 'CVSS:3.1/AV:L/AC:L/PR:N/UI:R/S:U/C:N/I:N/A:H',
    exploitTested: true,
    reproducerIncluded: true,
    customerPriority: 'Priority 2',
    stage: 'Submitted',
    complexity: 'Standard',
    submittedDate: daysAgo(2),
    lastUpdated: daysAgoTimestamp(1),
    ageDays: 2,
    embargo: false,
    duplicate: false,
    ltwlsupt_ticket_id: 'batch-3',
  },
  {
    uuid: 'v7',
    vulnerabilityId: 'LWL-2026-4407',
    purl: 'pkg:nuget/Newtonsoft.Json@13.0.1',
    componentName: 'Newtonsoft.Json',
    componentVersion: '13.0.1',
    title: 'Stack overflow during deep JSON parsing',
    cwe: 'CWE-674',
    description: 'DoS via deeply nested JSON structures',
    severity: 'Moderate',
    cvss: 5.3,
    cvssVector: 'CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:L',
    exploitTested: false,
    reproducerIncluded: false,
    customerPriority: 'Priority 3',
    stage: 'Submitted',
    complexity: 'Standard',
    submittedDate: daysAgo(1),
    lastUpdated: daysAgoTimestamp(0),
    ageDays: 1,
    embargo: false,
    duplicate: false,
    ltwlsupt_ticket_id: 'batch-3',
  },
  {
    uuid: 'v8',
    vulnerabilityId: 'LWL-2026-4408',
    purl: 'pkg:maven/org.apache.httpcomponents/httpclient@4.5.13',
    componentName: 'Apache HttpClient',
    componentVersion: '4.5.13',
    title: 'Certificate validation bypass',
    cwe: 'CWE-295',
    description: 'TLS certificate not properly validated under certain conditions',
    severity: 'Important',
    cvss: 7.4,
    cvssVector: 'CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:H/I:H/A:N',
    exploitTested: true,
    reproducerIncluded: false,
    customerPriority: 'Priority 2',
    stage: 'Submitted',
    complexity: 'Complex',
    submittedDate: daysAgo(5),
    lastUpdated: daysAgoTimestamp(4),
    ageDays: 5,
    embargo: false,
    duplicate: false,
    ltwlsupt_ticket_id: 'batch-2',
  },

  // Classified (7) - batch-2 (4), batch-3 (3)
  {
    uuid: 'v9',
    vulnerabilityId: 'LWL-2026-4301',
    purl: 'pkg:maven/org.apache.struts/struts2-core@2.5.30',
    componentName: 'struts2-core',
    componentVersion: '2.5.30',
    title: 'OGNL injection in tag attributes',
    cwe: 'CWE-917',
    description: 'Remote code execution via OGNL expression injection',
    severity: 'Critical',
    cvss: 9.8,
    cvssVector: 'CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H',
    exploitTested: true,
    reproducerIncluded: true,
    customerPriority: 'Priority 1',
    stage: 'Classified',
    complexity: 'Extensive',
    submittedDate: daysAgo(8),
    lastUpdated: daysAgoTimestamp(5),
    ageDays: 8,
    embargo: true,
    duplicate: false,
    ltwlsupt_ticket_id: 'batch-2',
  },
  {
    uuid: 'v10',
    vulnerabilityId: 'LWL-2026-4302',
    purl: 'pkg:pypi/django@4.1.0',
    componentName: 'Django',
    componentVersion: '4.1.0',
    title: 'SQL injection in QuerySet.extra()',
    cwe: 'CWE-89',
    description: 'SQL injection through unsanitized extra() parameters',
    severity: 'Important',
    cvss: 8.6,
    cvssVector: 'CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:C/C:H/I:N/A:N',
    exploitTested: true,
    reproducerIncluded: true,
    customerPriority: 'Priority 1',
    stage: 'Classified',
    complexity: 'Complex',
    submittedDate: daysAgo(7),
    lastUpdated: daysAgoTimestamp(4),
    ageDays: 7,
    embargo: false,
    duplicate: false,
    ltwlsupt_ticket_id: 'batch-2',
  },
  {
    uuid: 'v11',
    vulnerabilityId: 'LWL-2026-4303',
    purl: 'pkg:npm/lodash@4.17.21',
    componentName: 'lodash',
    componentVersion: '4.17.21',
    title: 'Prototype pollution in merge functions',
    cwe: 'CWE-1321',
    description: 'Object prototype pollution through recursive merge',
    severity: 'Important',
    cvss: 7.3,
    cvssVector: 'CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:L/A:L',
    exploitTested: false,
    reproducerIncluded: false,
    customerPriority: 'Priority 2',
    stage: 'Classified',
    complexity: 'Standard',
    submittedDate: daysAgo(6),
    lastUpdated: daysAgoTimestamp(3),
    ageDays: 6,
    embargo: false,
    duplicate: false,
    ltwlsupt_ticket_id: 'batch-3',
  },
  {
    uuid: 'v12',
    vulnerabilityId: 'LWL-2026-4304',
    purl: 'pkg:maven/org.cryptolib/cryptolib-core@1.70',
    componentName: 'CryptoLib Core',
    componentVersion: '1.70',
    title: 'Timing side-channel in ECDSA',
    cwe: 'CWE-208',
    description: 'Key recovery via timing analysis of ECDSA operations',
    severity: 'Moderate',
    cvss: 5.9,
    cvssVector: 'CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:H/I:N/A:N',
    exploitTested: true,
    reproducerIncluded: true,
    customerPriority: 'Priority 2',
    stage: 'Classified',
    complexity: 'Extensive',
    submittedDate: daysAgo(9),
    lastUpdated: daysAgoTimestamp(6),
    ageDays: 9,
    embargo: true,
    duplicate: false,
    ltwlsupt_ticket_id: 'batch-3',
  },
  {
    uuid: 'v13',
    vulnerabilityId: 'LWL-2026-4305',
    purl: 'pkg:pypi/flask@2.2.0',
    componentName: 'Flask',
    componentVersion: '2.2.0',
    title: 'Open redirect in URL handling',
    cwe: 'CWE-601',
    description: 'Unvalidated redirect allows phishing attacks',
    severity: 'Moderate',
    cvss: 4.7,
    cvssVector: 'CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:C/C:N/I:L/A:N',
    exploitTested: false,
    reproducerIncluded: false,
    customerPriority: 'Priority 4',
    stage: 'Classified',
    complexity: 'Standard',
    submittedDate: daysAgo(6),
    lastUpdated: daysAgoTimestamp(4),
    ageDays: 6,
    embargo: false,
    duplicate: false,
    ltwlsupt_ticket_id: 'batch-3',
  },
  {
    uuid: 'v14',
    vulnerabilityId: 'LWL-2026-4306',
    purl: 'pkg:npm/axios@1.3.0',
    componentName: 'axios',
    componentVersion: '1.3.0',
    title: 'SSRF via request interceptor bypass',
    cwe: 'CWE-918',
    description: 'Server-side request forgery through interceptor chain manipulation',
    severity: 'Important',
    cvss: 7.2,
    cvssVector: 'CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:H/I:L/A:N',
    exploitTested: true,
    reproducerIncluded: false,
    customerPriority: 'Priority 2',
    stage: 'Classified',
    complexity: 'Complex',
    submittedDate: daysAgo(10),
    lastUpdated: daysAgoTimestamp(7),
    ageDays: 10,
    embargo: false,
    duplicate: false,
    ltwlsupt_ticket_id: 'batch-2',
  },
  {
    uuid: 'v15',
    vulnerabilityId: 'LWL-2026-4307',
    purl: 'pkg:nuget/System.Text.Json@7.0.0',
    componentName: 'System.Text.Json',
    componentVersion: '7.0.0',
    title: 'Type confusion in polymorphic deserialization',
    cwe: 'CWE-843',
    description: 'Arbitrary type instantiation via crafted JSON payload',
    severity: 'Important',
    cvss: 8.1,
    cvssVector: 'CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:H/I:H/A:H',
    exploitTested: true,
    reproducerIncluded: true,
    customerPriority: 'Priority 1',
    stage: 'Classified',
    complexity: 'Extensive',
    submittedDate: daysAgo(11),
    lastUpdated: daysAgoTimestamp(8),
    ageDays: 11,
    embargo: false,
    duplicate: false,
    ltwlsupt_ticket_id: 'batch-2',
  },

  // Fix in Progress (9) - batch-2 (7), batch-1 (2)
  {
    uuid: 'v16',
    vulnerabilityId: 'LWL-2026-4201',
    purl: 'pkg:maven/org.apache.tomcat/tomcat-catalina@9.0.65',
    componentName: 'Tomcat Catalina',
    componentVersion: '9.0.65',
    title: 'Request smuggling via chunked encoding',
    cwe: 'CWE-444',
    description: 'HTTP request smuggling through malformed chunked transfer encoding',
    severity: 'Important',
    cvss: 8.1,
    cvssVector: 'CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:H/I:H/A:H',
    exploitTested: true,
    reproducerIncluded: true,
    customerPriority: 'Priority 1',
    stage: 'Fix in Progress',
    complexity: 'Extensive',
    submittedDate: daysAgo(15),
    lastUpdated: daysAgoTimestamp(3),
    ageDays: 15,
    embargo: false,
    duplicate: false,
    ltwlsupt_ticket_id: 'batch-2',
  },
  {
    uuid: 'v17',
    vulnerabilityId: 'LWL-2026-4202',
    purl: 'pkg:pypi/numpy@1.24.0',
    componentName: 'NumPy',
    componentVersion: '1.24.0',
    title: 'Buffer overflow in array reshape',
    cwe: 'CWE-120',
    description: 'Heap buffer overflow through crafted array dimensions',
    severity: 'Important',
    cvss: 7.8,
    cvssVector: 'CVSS:3.1/AV:L/AC:L/PR:N/UI:R/S:U/C:H/I:H/A:H',
    exploitTested: true,
    reproducerIncluded: true,
    customerPriority: 'Priority 2',
    stage: 'Fix in Progress',
    complexity: 'Complex',
    submittedDate: daysAgo(12),
    lastUpdated: daysAgoTimestamp(2),
    ageDays: 12,
    embargo: false,
    duplicate: false,
    ltwlsupt_ticket_id: 'batch-2',
  },
  {
    uuid: 'v18',
    vulnerabilityId: 'LWL-2026-4203',
    purl: 'pkg:npm/jsonwebtoken@9.0.0',
    componentName: 'jsonwebtoken',
    componentVersion: '9.0.0',
    title: 'Algorithm confusion in token verification',
    cwe: 'CWE-327',
    description: 'JWT signature bypass through algorithm switching attack',
    severity: 'Critical',
    cvss: 9.1,
    cvssVector: 'CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:N',
    exploitTested: true,
    reproducerIncluded: true,
    customerPriority: 'Priority 1',
    stage: 'Fix in Progress',
    complexity: 'Complex',
    submittedDate: daysAgo(14),
    lastUpdated: daysAgoTimestamp(1),
    ageDays: 14,
    embargo: true,
    duplicate: false,
    ltwlsupt_ticket_id: 'batch-2',
  },
  {
    uuid: 'v19',
    vulnerabilityId: 'LWL-2026-4204',
    purl: 'pkg:maven/com.google.guava/guava@31.1-jre',
    componentName: 'Guava',
    componentVersion: '31.1-jre',
    title: 'Temporary file information disclosure',
    cwe: 'CWE-377',
    description: 'Predictable temp file names allow information leakage',
    severity: 'Moderate',
    cvss: 5.5,
    cvssVector: 'CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:H/I:N/A:N',
    exploitTested: false,
    reproducerIncluded: false,
    customerPriority: 'Priority 3',
    stage: 'Fix in Progress',
    complexity: 'Standard',
    submittedDate: daysAgo(10),
    lastUpdated: daysAgoTimestamp(4),
    ageDays: 10,
    embargo: false,
    duplicate: false,
    ltwlsupt_ticket_id: 'batch-2',
  },
  {
    uuid: 'v20',
    vulnerabilityId: 'LWL-2026-4205',
    purl: 'pkg:pypi/pillow@9.4.0',
    componentName: 'Pillow',
    componentVersion: '9.4.0',
    title: 'Heap overflow in TIFF decoder',
    cwe: 'CWE-122',
    description: 'Remote code execution via crafted TIFF image',
    severity: 'Important',
    cvss: 8.8,
    cvssVector: 'CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:U/C:H/I:H/A:H',
    exploitTested: true,
    reproducerIncluded: true,
    customerPriority: 'Priority 1',
    stage: 'Fix in Progress',
    complexity: 'Extensive',
    submittedDate: daysAgo(18),
    lastUpdated: daysAgoTimestamp(5),
    ageDays: 18,
    embargo: false,
    duplicate: false,
    ltwlsupt_ticket_id: 'batch-1',
  },
  {
    uuid: 'v21',
    vulnerabilityId: 'LWL-2026-4206',
    purl: 'pkg:nuget/Microsoft.Data.SqlClient@5.1.0',
    componentName: 'Microsoft.Data.SqlClient',
    componentVersion: '5.1.0',
    title: 'Connection string injection',
    cwe: 'CWE-99',
    description: 'SQL Server connection hijacking through crafted connection strings',
    severity: 'Important',
    cvss: 7.5,
    cvssVector: 'CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:H/A:N',
    exploitTested: true,
    reproducerIncluded: false,
    customerPriority: 'Priority 2',
    stage: 'Fix in Progress',
    complexity: 'Complex',
    submittedDate: daysAgo(13),
    lastUpdated: daysAgoTimestamp(6),
    ageDays: 13,
    embargo: false,
    duplicate: false,
    ltwlsupt_ticket_id: 'batch-2',
  },
  {
    uuid: 'v22',
    vulnerabilityId: 'LWL-2026-4207',
    purl: 'pkg:maven/org.yaml/snakeyaml@1.33',
    componentName: 'SnakeYAML',
    componentVersion: '1.33',
    title: 'Arbitrary code execution via YAML deserialization',
    cwe: 'CWE-502',
    description: 'RCE through unsafe YAML constructor usage',
    severity: 'Critical',
    cvss: 9.8,
    cvssVector: 'CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H',
    exploitTested: true,
    reproducerIncluded: true,
    customerPriority: 'Priority 1',
    stage: 'Fix in Progress',
    complexity: 'Extensive',
    submittedDate: daysAgo(20),
    lastUpdated: daysAgoTimestamp(2),
    ageDays: 20,
    embargo: false,
    duplicate: false,
    ltwlsupt_ticket_id: 'batch-1',
  },
  {
    uuid: 'v23',
    vulnerabilityId: 'LWL-2026-4208',
    purl: 'pkg:npm/minimatch@3.0.4',
    componentName: 'minimatch',
    componentVersion: '3.0.4',
    title: 'ReDoS in brace expansion',
    cwe: 'CWE-1333',
    description: 'Regular expression denial of service through crafted glob patterns',
    severity: 'Moderate',
    cvss: 5.3,
    cvssVector: 'CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:L',
    exploitTested: false,
    reproducerIncluded: false,
    customerPriority: 'Priority 4',
    stage: 'Fix in Progress',
    complexity: 'Standard',
    submittedDate: daysAgo(11),
    lastUpdated: daysAgoTimestamp(7),
    ageDays: 11,
    embargo: false,
    duplicate: false,
    ltwlsupt_ticket_id: 'batch-2',
  },
  {
    uuid: 'v24',
    vulnerabilityId: 'LWL-2026-4209',
    purl: 'pkg:pypi/cryptography@39.0.0',
    componentName: 'cryptography',
    componentVersion: '39.0.0',
    title: 'NULL pointer dereference in X.509 parsing',
    cwe: 'CWE-476',
    description: 'DoS through malformed X.509 certificate',
    severity: 'Moderate',
    cvss: 5.9,
    cvssVector: 'CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:N/I:N/A:H',
    exploitTested: true,
    reproducerIncluded: true,
    customerPriority: 'Priority 3',
    stage: 'Fix in Progress',
    complexity: 'Standard',
    submittedDate: daysAgo(9),
    lastUpdated: daysAgoTimestamp(3),
    ageDays: 9,
    embargo: false,
    duplicate: false,
    ltwlsupt_ticket_id: 'batch-2',
  },

  // Validation (8) - batch-2 (4), batch-1 (3), batch-3 (1)
  {
    uuid: 'v25',
    vulnerabilityId: 'LWL-2026-4101',
    purl: 'pkg:maven/org.apache.commons/commons-text@1.9',
    componentName: 'Apache Commons Text',
    componentVersion: '1.9',
    title: 'Text4Shell - StringSubstitutor interpolation',
    cwe: 'CWE-94',
    description: 'Code injection through uncontrolled string interpolation',
    severity: 'Critical',
    cvss: 9.8,
    cvssVector: 'CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H',
    exploitTested: true,
    reproducerIncluded: true,
    customerPriority: 'Priority 1',
    stage: 'Validation',
    complexity: 'Extensive',
    submittedDate: daysAgo(25),
    lastUpdated: daysAgoTimestamp(2),
    ageDays: 25,
    embargo: false,
    duplicate: false,
    ltwlsupt_ticket_id: 'batch-1',
  },
  {
    uuid: 'v26',
    vulnerabilityId: 'LWL-2026-4102',
    purl: 'pkg:pypi/urllib3@1.26.15',
    componentName: 'urllib3',
    componentVersion: '1.26.15',
    title: 'CRLF injection in request headers',
    cwe: 'CWE-93',
    description: 'HTTP header injection through crafted URL parameters',
    severity: 'Moderate',
    cvss: 6.1,
    cvssVector: 'CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:C/C:L/I:L/A:N',
    exploitTested: false,
    reproducerIncluded: false,
    customerPriority: 'Priority 3',
    stage: 'Validation',
    complexity: 'Standard',
    submittedDate: daysAgo(20),
    lastUpdated: daysAgoTimestamp(4),
    ageDays: 20,
    embargo: false,
    duplicate: false,
    ltwlsupt_ticket_id: 'batch-2',
  },
  {
    uuid: 'v27',
    vulnerabilityId: 'LWL-2026-4103',
    purl: 'pkg:npm/semver@7.3.8',
    componentName: 'semver',
    componentVersion: '7.3.8',
    title: 'ReDoS in version range parsing',
    cwe: 'CWE-1333',
    description: 'Denial of service through crafted semver range strings',
    severity: 'Moderate',
    cvss: 5.3,
    cvssVector: 'CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:L',
    exploitTested: false,
    reproducerIncluded: false,
    customerPriority: 'Priority 4',
    stage: 'Validation',
    complexity: 'Standard',
    submittedDate: daysAgo(18),
    lastUpdated: daysAgoTimestamp(5),
    ageDays: 18,
    embargo: false,
    duplicate: false,
    ltwlsupt_ticket_id: 'batch-2',
  },
  {
    uuid: 'v28',
    vulnerabilityId: 'LWL-2026-4104',
    purl: 'pkg:maven/io.netty/netty-codec-http@4.1.86.Final',
    componentName: 'Netty',
    componentVersion: '4.1.86.Final',
    title: 'HTTP/2 CONTINUATION frame flooding',
    cwe: 'CWE-400',
    description: 'Memory exhaustion via excessive CONTINUATION frames',
    severity: 'Important',
    cvss: 7.5,
    cvssVector: 'CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H',
    exploitTested: true,
    reproducerIncluded: true,
    customerPriority: 'Priority 2',
    stage: 'Validation',
    complexity: 'Complex',
    submittedDate: daysAgo(22),
    lastUpdated: daysAgoTimestamp(3),
    ageDays: 22,
    embargo: false,
    duplicate: false,
    ltwlsupt_ticket_id: 'batch-1',
  },
  {
    uuid: 'v29',
    vulnerabilityId: 'LWL-2026-4105',
    purl: 'pkg:nuget/System.Security.Cryptography.Xml@7.0.0',
    componentName: 'System.Security.Cryptography.Xml',
    componentVersion: '7.0.0',
    title: 'XML signature wrapping attack',
    cwe: 'CWE-347',
    description: 'Signature verification bypass in XML digital signatures',
    severity: 'Important',
    cvss: 7.5,
    cvssVector: 'CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:H/A:N',
    exploitTested: true,
    reproducerIncluded: false,
    customerPriority: 'Priority 2',
    stage: 'Validation',
    complexity: 'Extensive',
    submittedDate: daysAgo(28),
    lastUpdated: daysAgoTimestamp(6),
    ageDays: 28,
    embargo: false,
    duplicate: false,
    ltwlsupt_ticket_id: 'batch-2',
  },
  {
    uuid: 'v30',
    vulnerabilityId: 'LWL-2026-4106',
    purl: 'pkg:pypi/paramiko@3.1.0',
    componentName: 'Paramiko',
    componentVersion: '3.1.0',
    title: 'Authentication bypass in SFTP subsystem',
    cwe: 'CWE-287',
    description: 'SSH authentication bypass under race condition',
    severity: 'Critical',
    cvss: 9.1,
    cvssVector: 'CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:N',
    exploitTested: true,
    reproducerIncluded: true,
    customerPriority: 'Priority 1',
    stage: 'Validation',
    complexity: 'Extensive',
    submittedDate: daysAgo(30),
    lastUpdated: daysAgoTimestamp(1),
    ageDays: 30,
    embargo: true,
    duplicate: false,
    ltwlsupt_ticket_id: 'batch-1',
  },
  {
    uuid: 'v31',
    vulnerabilityId: 'LWL-2026-4107',
    purl: 'pkg:maven/com.h2database/h2@2.1.214',
    componentName: 'H2 Database',
    componentVersion: '2.1.214',
    title: 'Remote code execution via JDBC URL',
    cwe: 'CWE-94',
    description: 'RCE through crafted JDBC connection URL parameters',
    severity: 'Critical',
    cvss: 9.8,
    cvssVector: 'CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H',
    exploitTested: true,
    reproducerIncluded: true,
    customerPriority: 'Priority 1',
    stage: 'Validation',
    complexity: 'Extensive',
    submittedDate: daysAgo(32),
    lastUpdated: daysAgoTimestamp(4),
    ageDays: 32,
    embargo: false,
    duplicate: false,
    ltwlsupt_ticket_id: 'batch-2',
  },
  {
    uuid: 'v32',
    vulnerabilityId: 'LWL-2026-4108',
    purl: 'pkg:npm/ua-parser-js@0.7.33',
    componentName: 'ua-parser-js',
    componentVersion: '0.7.33',
    title: 'ReDoS in User-Agent parsing',
    cwe: 'CWE-1333',
    description: 'Regular expression denial of service in UA string parsing',
    severity: 'Moderate',
    cvss: 5.3,
    cvssVector: 'CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:L',
    exploitTested: false,
    reproducerIncluded: false,
    customerPriority: 'Priority 4',
    stage: 'Validation',
    complexity: 'Standard',
    submittedDate: daysAgo(19),
    lastUpdated: daysAgoTimestamp(7),
    ageDays: 19,
    embargo: false,
    duplicate: true,
    duplicateOf: 'LWL-2026-4027',
    ltwlsupt_ticket_id: 'batch-3',
  },

  // Lightwell Network (7) - batch-1 (4), batch-3 (1), batch-2 (2)
  {
    uuid: 'v33',
    vulnerabilityId: 'LWL-2026-4001',
    purl: 'pkg:maven/org.apache.shiro/shiro-core@1.10.0',
    componentName: 'Apache Shiro',
    componentVersion: '1.10.0',
    title: 'Authentication bypass via path traversal',
    cwe: 'CWE-287',
    description: 'Auth bypass using path normalization inconsistencies',
    severity: 'Critical',
    cvss: 9.8,
    cvssVector: 'CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H',
    exploitTested: true,
    reproducerIncluded: true,
    customerPriority: 'Priority 1',
    stage: 'Lightwell Network',
    complexity: 'Extensive',
    submittedDate: daysAgo(35),
    lastUpdated: daysAgoTimestamp(2),
    ageDays: 35,
    embargo: false,
    duplicate: false,
    ltwlsupt_ticket_id: 'batch-1',
  },
  {
    uuid: 'v34',
    vulnerabilityId: 'LWL-2026-4002',
    purl: 'pkg:pypi/pyyaml@6.0',
    componentName: 'PyYAML',
    componentVersion: '6.0',
    title: 'Arbitrary code execution via load()',
    cwe: 'CWE-502',
    description: 'RCE through unsafe YAML deserialization',
    severity: 'Important',
    cvss: 8.1,
    cvssVector: 'CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:H/I:H/A:H',
    exploitTested: true,
    reproducerIncluded: true,
    customerPriority: 'Priority 1',
    stage: 'Lightwell Network',
    complexity: 'Complex',
    submittedDate: daysAgo(30),
    lastUpdated: daysAgoTimestamp(5),
    ageDays: 30,
    embargo: false,
    duplicate: false,
    ltwlsupt_ticket_id: 'batch-1',
  },
  {
    uuid: 'v35',
    vulnerabilityId: 'LWL-2026-4003',
    purl: 'pkg:npm/node-forge@1.3.1',
    componentName: 'node-forge',
    componentVersion: '1.3.1',
    title: 'RSA PKCS#1 v1.5 signature forgery',
    cwe: 'CWE-347',
    description: 'Signature verification bypass in RSA implementation',
    severity: 'Important',
    cvss: 7.5,
    cvssVector: 'CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:H/A:N',
    exploitTested: true,
    reproducerIncluded: false,
    customerPriority: 'Priority 2',
    stage: 'Lightwell Network',
    complexity: 'Complex',
    submittedDate: daysAgo(28),
    lastUpdated: daysAgoTimestamp(7),
    ageDays: 28,
    embargo: false,
    duplicate: false,
    ltwlsupt_ticket_id: 'batch-2',
  },
  {
    uuid: 'v36',
    vulnerabilityId: 'LWL-2026-4004',
    purl: 'pkg:maven/org.hibernate/hibernate-core@5.6.14.Final',
    componentName: 'Hibernate',
    componentVersion: '5.6.14.Final',
    title: 'SQL injection in HQL named parameters',
    cwe: 'CWE-89',
    description: 'SQL injection through crafted HQL parameter names',
    severity: 'Important',
    cvss: 8.6,
    cvssVector: 'CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:C/C:H/I:N/A:N',
    exploitTested: true,
    reproducerIncluded: true,
    customerPriority: 'Priority 1',
    stage: 'Lightwell Network',
    complexity: 'Complex',
    submittedDate: daysAgo(33),
    lastUpdated: daysAgoTimestamp(3),
    ageDays: 33,
    embargo: false,
    duplicate: false,
    ltwlsupt_ticket_id: 'batch-1',
  },
  {
    uuid: 'v37',
    vulnerabilityId: 'LWL-2026-4005',
    purl: 'pkg:nuget/Azure.Identity@1.8.0',
    componentName: 'Azure.Identity',
    componentVersion: '1.8.0',
    title: 'Token cache poisoning',
    cwe: 'CWE-345',
    description: 'Authentication token manipulation through shared cache',
    severity: 'Moderate',
    cvss: 6.5,
    cvssVector: 'CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:H/I:N/A:N',
    exploitTested: false,
    reproducerIncluded: false,
    customerPriority: 'Priority 3',
    stage: 'Lightwell Network',
    complexity: 'Standard',
    submittedDate: daysAgo(25),
    lastUpdated: daysAgoTimestamp(8),
    ageDays: 25,
    embargo: false,
    duplicate: false,
    ltwlsupt_ticket_id: 'batch-3',
  },
  {
    uuid: 'v38',
    vulnerabilityId: 'LWL-2026-4006',
    purl: 'pkg:pypi/jinja2@3.1.2',
    componentName: 'Jinja2',
    componentVersion: '3.1.2',
    title: 'Sandbox escape via attr filter',
    cwe: 'CWE-693',
    description: 'Template sandbox bypass through attribute access',
    severity: 'Important',
    cvss: 8.1,
    cvssVector: 'CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:H/I:H/A:H',
    exploitTested: true,
    reproducerIncluded: true,
    customerPriority: 'Priority 1',
    stage: 'Lightwell Network',
    complexity: 'Complex',
    submittedDate: daysAgo(31),
    lastUpdated: daysAgoTimestamp(4),
    ageDays: 31,
    embargo: false,
    duplicate: false,
    ltwlsupt_ticket_id: 'batch-1',
  },
  {
    uuid: 'v39',
    vulnerabilityId: 'LWL-2026-4007',
    purl: 'pkg:maven/net.minidev/json-smart@2.4.8',
    componentName: 'json-smart',
    componentVersion: '2.4.8',
    title: 'Stack overflow in JSON parser',
    cwe: 'CWE-674',
    description: 'DoS through deeply nested JSON structures',
    severity: 'Moderate',
    cvss: 5.3,
    cvssVector: 'CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:L',
    exploitTested: false,
    reproducerIncluded: false,
    customerPriority: 'Priority 4',
    stage: 'Lightwell Network',
    complexity: 'Standard',
    submittedDate: daysAgo(26),
    lastUpdated: daysAgoTimestamp(9),
    ageDays: 26,
    embargo: false,
    duplicate: true,
    duplicateOf: 'LWL-2026-3998',
    ltwlsupt_ticket_id: 'batch-2',
  },

  // Lightwell Network (formerly Upstreaming) (6) - batch-1 (3), batch-3 (3)
  {
    uuid: 'v40',
    vulnerabilityId: 'LWL-2026-3901',
    purl: 'pkg:maven/org.eclipse.jetty/jetty-server@11.0.13',
    componentName: 'Jetty',
    componentVersion: '11.0.13',
    title: 'HTTP response splitting',
    cwe: 'CWE-113',
    description: 'Response header injection through crafted request parameters',
    severity: 'Important',
    cvss: 7.5,
    cvssVector: 'CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:H/A:N',
    exploitTested: true,
    reproducerIncluded: true,
    customerPriority: 'Priority 2',
    stage: 'Lightwell Network',
    complexity: 'Complex',
    submittedDate: daysAgo(38),
    lastUpdated: daysAgoTimestamp(10),
    ageDays: 38,
    embargo: true,
    duplicate: false,
    ltwlsupt_ticket_id: 'batch-1',
  },
  {
    uuid: 'v41',
    vulnerabilityId: 'LWL-2026-3902',
    purl: 'pkg:pypi/setuptools@67.0.0',
    componentName: 'setuptools',
    componentVersion: '67.0.0',
    title: 'Command injection in package install',
    cwe: 'CWE-78',
    description: 'OS command injection through crafted package metadata',
    severity: 'Important',
    cvss: 8.8,
    cvssVector: 'CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:U/C:H/I:H/A:H',
    exploitTested: true,
    reproducerIncluded: true,
    customerPriority: 'Priority 1',
    stage: 'Lightwell Network',
    complexity: 'Extensive',
    submittedDate: daysAgo(40),
    lastUpdated: daysAgoTimestamp(12),
    ageDays: 40,
    embargo: false,
    duplicate: false,
    ltwlsupt_ticket_id: 'batch-3',
  },
  {
    uuid: 'v42',
    vulnerabilityId: 'LWL-2026-3903',
    purl: 'pkg:npm/tar@6.1.13',
    componentName: 'tar',
    componentVersion: '6.1.13',
    title: 'Arbitrary file overwrite via symlink',
    cwe: 'CWE-59',
    description: 'Path traversal through symbolic link following during extraction',
    severity: 'Important',
    cvss: 7.5,
    cvssVector: 'CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:H/A:N',
    exploitTested: true,
    reproducerIncluded: false,
    customerPriority: 'Priority 2',
    stage: 'Lightwell Network',
    complexity: 'Complex',
    submittedDate: daysAgo(36),
    lastUpdated: daysAgoTimestamp(8),
    ageDays: 36,
    embargo: false,
    duplicate: false,
    ltwlsupt_ticket_id: 'batch-1',
  },
  {
    uuid: 'v43',
    vulnerabilityId: 'LWL-2026-3904',
    purl: 'pkg:maven/org.apache.poi/poi@5.2.3',
    componentName: 'Apache POI',
    componentVersion: '5.2.3',
    title: 'XXE in OOXML document processing',
    cwe: 'CWE-611',
    description: 'XML external entity injection via crafted Office documents',
    severity: 'Moderate',
    cvss: 6.5,
    cvssVector: 'CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:H/I:N/A:N',
    exploitTested: false,
    reproducerIncluded: false,
    customerPriority: 'Priority 3',
    stage: 'Lightwell Network',
    complexity: 'Standard',
    submittedDate: daysAgo(35),
    lastUpdated: daysAgoTimestamp(11),
    ageDays: 35,
    embargo: false,
    duplicate: false,
    ltwlsupt_ticket_id: 'batch-3',
  },
  {
    uuid: 'v44',
    vulnerabilityId: 'LWL-2026-3905',
    purl: 'pkg:nuget/SecureNet.Cryptography@2.1.1',
    componentName: 'SecureNet.Cryptography',
    componentVersion: '2.1.1',
    title: 'LDAP injection in certificate lookup',
    cwe: 'CWE-90',
    description: 'LDAP injection through certificate subject DN',
    severity: 'Moderate',
    cvss: 6.1,
    cvssVector: 'CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:C/C:L/I:L/A:N',
    exploitTested: false,
    reproducerIncluded: false,
    customerPriority: 'Priority 3',
    stage: 'Lightwell Network',
    complexity: 'Standard',
    submittedDate: daysAgo(34),
    lastUpdated: daysAgoTimestamp(9),
    ageDays: 34,
    embargo: false,
    duplicate: false,
    ltwlsupt_ticket_id: 'batch-3',
  },
  {
    uuid: 'v45',
    vulnerabilityId: 'LWL-2026-3906',
    purl: 'pkg:pypi/lxml@4.9.2',
    componentName: 'lxml',
    componentVersion: '4.9.2',
    title: 'Use-after-free in HTML parser',
    cwe: 'CWE-416',
    description: 'Memory corruption through crafted HTML document',
    severity: 'Important',
    cvss: 8.1,
    cvssVector: 'CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:H/I:H/A:H',
    exploitTested: true,
    reproducerIncluded: true,
    customerPriority: 'Priority 1',
    stage: 'Lightwell Network',
    complexity: 'Extensive',
    submittedDate: daysAgo(42),
    lastUpdated: daysAgoTimestamp(14),
    ageDays: 42,
    embargo: false,
    duplicate: false,
    ltwlsupt_ticket_id: 'batch-1',
  },

  // Lightwell Network (formerly Published) (7) - batch-1 (6), batch-3 (1)
  {
    uuid: 'v46',
    vulnerabilityId: 'LWL-2026-3801',
    purl: 'pkg:maven/org.postgresql/postgresql@42.5.1',
    componentName: 'PostgreSQL JDBC',
    componentVersion: '42.5.1',
    title: 'SQL injection via connection property',
    cwe: 'CWE-89',
    description: 'SQL injection through JDBC connection properties',
    severity: 'Critical',
    cvss: 9.8,
    cvssVector: 'CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H',
    exploitTested: true,
    reproducerIncluded: true,
    customerPriority: 'Priority 1',
    stage: 'Lightwell Network',
    complexity: 'Extensive',
    submittedDate: daysAgo(45),
    lastUpdated: daysAgoTimestamp(15),
    ageDays: 45,
    embargo: false,
    duplicate: false,
    ltwlsupt_ticket_id: 'batch-1',
  },
  {
    uuid: 'v47',
    vulnerabilityId: 'LWL-2026-3802',
    purl: 'pkg:pypi/certifi@2022.12.7',
    componentName: 'certifi',
    componentVersion: '2022.12.7',
    title: 'Inclusion of revoked root certificate',
    cwe: 'CWE-295',
    description: 'Trust of revoked CA certificate in bundle',
    severity: 'Moderate',
    cvss: 5.3,
    cvssVector: 'CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:L/A:N',
    exploitTested: false,
    reproducerIncluded: false,
    customerPriority: 'Priority 3',
    stage: 'Lightwell Network',
    complexity: 'Standard',
    submittedDate: daysAgo(40),
    lastUpdated: daysAgoTimestamp(18),
    ageDays: 40,
    embargo: false,
    duplicate: false,
    ltwlsupt_ticket_id: 'batch-1',
  },
  {
    uuid: 'v48',
    vulnerabilityId: 'LWL-2026-3803',
    purl: 'pkg:npm/glob-parent@5.1.2',
    componentName: 'glob-parent',
    componentVersion: '5.1.2',
    title: 'ReDoS in brace expansion',
    cwe: 'CWE-1333',
    description: 'Regular expression denial of service',
    severity: 'Moderate',
    cvss: 5.3,
    cvssVector: 'CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:L',
    exploitTested: false,
    reproducerIncluded: false,
    customerPriority: 'Priority 4',
    stage: 'Lightwell Network',
    complexity: 'Standard',
    submittedDate: daysAgo(38),
    lastUpdated: daysAgoTimestamp(16),
    ageDays: 38,
    embargo: false,
    duplicate: false,
    ltwlsupt_ticket_id: 'batch-1',
  },
  {
    uuid: 'v49',
    vulnerabilityId: 'LWL-2026-3804',
    purl: 'pkg:maven/com.squareup.okhttp3/okhttp@4.10.0',
    componentName: 'OkHttp',
    componentVersion: '4.10.0',
    title: 'Header injection in HTTP/2',
    cwe: 'CWE-113',
    description: 'Response splitting through HTTP/2 pseudo-headers',
    severity: 'Important',
    cvss: 7.5,
    cvssVector: 'CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:H/A:N',
    exploitTested: true,
    reproducerIncluded: true,
    customerPriority: 'Priority 2',
    stage: 'Lightwell Network',
    complexity: 'Complex',
    submittedDate: daysAgo(43),
    lastUpdated: daysAgoTimestamp(13),
    ageDays: 43,
    embargo: false,
    duplicate: false,
    ltwlsupt_ticket_id: 'batch-1',
  },
  {
    uuid: 'v50',
    vulnerabilityId: 'LWL-2026-3805',
    purl: 'pkg:nuget/Microsoft.AspNetCore.App@7.0.0',
    componentName: 'ASP.NET Core',
    componentVersion: '7.0.0',
    title: 'CORS policy bypass',
    cwe: 'CWE-942',
    description: 'Cross-origin resource sharing policy circumvention',
    severity: 'Moderate',
    cvss: 6.1,
    cvssVector: 'CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:C/C:L/I:L/A:N',
    exploitTested: false,
    reproducerIncluded: false,
    customerPriority: 'Priority 3',
    stage: 'Lightwell Network',
    complexity: 'Standard',
    submittedDate: daysAgo(37),
    lastUpdated: daysAgoTimestamp(17),
    ageDays: 37,
    embargo: false,
    duplicate: false,
    ltwlsupt_ticket_id: 'batch-3',
  },
  {
    uuid: 'v51',
    vulnerabilityId: 'LWL-2026-3806',
    purl: 'pkg:pypi/werkzeug@2.2.3',
    componentName: 'Werkzeug',
    componentVersion: '2.2.3',
    title: 'Path traversal in SharedDataMiddleware',
    cwe: 'CWE-22',
    description: 'Arbitrary file read through path traversal',
    severity: 'Important',
    cvss: 7.5,
    cvssVector: 'CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:N',
    exploitTested: true,
    reproducerIncluded: false,
    customerPriority: 'Priority 2',
    stage: 'Lightwell Network',
    complexity: 'Complex',
    submittedDate: daysAgo(41),
    lastUpdated: daysAgoTimestamp(19),
    ageDays: 41,
    embargo: false,
    duplicate: false,
    ltwlsupt_ticket_id: 'batch-1',
  },
  {
    uuid: 'v52',
    vulnerabilityId: 'LWL-2026-3807',
    purl: 'pkg:maven/org.codehaus.plexus/plexus-utils@3.4.2',
    componentName: 'plexus-utils',
    componentVersion: '3.4.2',
    title: 'Command injection in Commandline class',
    cwe: 'CWE-78',
    description: 'OS command injection through argument expansion',
    severity: 'Important',
    cvss: 8.1,
    cvssVector: 'CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:H/I:H/A:H',
    exploitTested: true,
    reproducerIncluded: true,
    customerPriority: 'Priority 1',
    stage: 'Lightwell Network',
    complexity: 'Complex',
    submittedDate: daysAgo(44),
    lastUpdated: daysAgoTimestamp(20),
    ageDays: 44,
    embargo: false,
    duplicate: false,
    ltwlsupt_ticket_id: 'batch-1',
  },
];
